# Complete example at <https://github.com/cosmtrek/air/blob/master/air_example.toml>
root = "."
tmp_dir = "tmp"
testdata_dir = "testdata"

[build]
  args_bin = []
  bin = "./tmp/server"
  cmd = "CGO_ENABLED=1 go build -o ./tmp/server ./cmd/api/main.go"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["(\\.null-ls.*|_test)\\.go"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
